import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design system — Route Precision System
        "outline-variant": "#bfc9c5",
        "tertiary-container": "#623c00",
        "surface-container-low": "#f2f4f6",
        "surface-bright": "#f7f9fb",
        "inverse-primary": "#98d2c5",
        "surface-dim": "#d8dadc",
        "on-background": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "secondary-fixed-dim": "#3cddc7",
        "surface-tint": "#2f685e",
        secondary: "#006b5f",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        surface: "#f7f9fb",
        tertiary: "#442800",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#f69f0d",
        "primary-fixed": "#b3eee1",
        "on-primary-fixed": "#00201b",
        "on-primary": "#ffffff",
        background: "#f7f9fb",
        "on-secondary-container": "#007165",
        outline: "#707976",
        "inverse-on-surface": "#eff1f3",
        "on-primary-container": "#83bdb1",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#98d2c5",
        primary: "#00352e",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "secondary-fixed": "#62fae3",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "on-surface-variant": "#404946",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        "primary-container": "#0d4d44",
        "secondary-container": "#62fae3",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffddb8",
        // Route badge colors
        "route-fastest": "#00352e",
        "route-greenest": "#006b5f",
        "route-cheapest": "#442800",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sidebar_width: "360px",
        gutter: "16px",
        sm: "8px",
        xs: "4px",
        lg: "24px",
        base: "4px",
        md: "16px",
        xl: "40px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
