import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // PathFinder — Forest Green design system
        // Palette: #DAD7CD · #A3B18A · #588157 · #3A5A40 · #344E41
        "outline-variant": "#A3B18A",
        "tertiary-container": "#3A5A40",
        "surface-container-low": "#eef1ec",
        "surface-bright": "#f5f7f2",
        "inverse-primary": "#A3B18A",
        "surface-dim": "#c8d0c4",
        "on-background": "#1a2e1e",
        "surface-container-highest": "#d4dbd0",
        "surface-container-high": "#dce4d8",
        "secondary-fixed-dim": "#588157",
        "surface-tint": "#588157",
        secondary: "#3A5A40",
        "surface-variant": "#dce4d8",
        "on-error": "#ffffff",
        surface: "#f5f7f2",
        tertiary: "#344E41",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#A3B18A",
        "primary-fixed": "#DAD7CD",
        "on-primary-fixed": "#1a2e1e",
        "on-primary": "#ffffff",
        background: "#f5f7f2",
        "on-secondary-container": "#344E41",
        outline: "#588157",
        "inverse-on-surface": "#eef1ec",
        "on-primary-container": "#A3B18A",
        "inverse-surface": "#1a2e1e",
        "primary-fixed-dim": "#A3B18A",
        primary: "#344E41",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "secondary-fixed": "#A3B18A",
        "on-secondary": "#ffffff",
        "on-surface": "#1a2e1e",
        "on-surface-variant": "#3A5A40",
        "surface-container": "#e4ebe0",
        "error-container": "#ffdad6",
        "primary-container": "#3A5A40",
        "secondary-container": "#DAD7CD",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#DAD7CD",
        // Route badge colors
        "route-fastest": "#344E41",
        "route-greenest": "#588157",
        "route-cheapest": "#3A5A40",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sidebar_width: "360px",
        gutter: "16px",
        sm: "8px",
        xs: "4px",
        lg: "24px",
        base: "4px",
        md: "16px",
        xl: "40px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
